### ISSUE TITLE
Can you decode bnet server packages?

### ISSUE THREAD

**Issue by AncientiCe** [nielsAD/gowarcraft3#3]
Hi,

Awesome work.
1.So can you decode packages of events like : 
- search for matchmaking 1v1
- game found
- opponent
- who's the host

2. Can you interact with this communication and override ?

3. Is there any way to get in touch?

Best regards,
iCe

**Comment by nielsAD** [comment]
The Battle.net protocol for WC3 has changed since patch 1.30.2 (released a few months ago), which means a lot of Battle.net code in this repository is outdated and will only work for private servers such as PvPGN.

For now, you can still decode packets for ladder games (see [w3gsdump](https://github.com/nielsAD/gowarcraft3/tree/master/cmd/w3gsdump)), but I assume that might change in the future if Blizzard gets around to updating the game protocol as well. Look at https://github.com/dethredic/WC3StreamerOverlay for a project that uses this approach and does what you're describing in point 1.

I'm not aware of a solution that lets you edit packets on the wire, pcap only lets you capture and observe them.

**Comment by AncientiCe** [comment]
Hey, thanks for the answer.

I'm interesting in implementing the following ideas:
1. patch a pvpgn server to provide host bot experience in PG (the quick
game features) since port forwarding was a pain.
2. Upgrade a pvpgn server from the latest patch available 1.28.5 to 1.29
for starters and 1.30 later. This is harder since there was no update on
the w3lh repository.

So i was curious if i can find a solution into your repo.
If so, please let me know.

Best regards,
iCe

**Comment by nielsAD** [comment]
I'm afraid this repo will not be too useful for you in that case. Battle.net stuff has been kept to a minimum, and it's mostly just chat functionality at the moment. For the quick game features, I think you get far by configuring/editing PvPGN.

Yeah, you can indeed intercept packets and act as a man-in-the-middle, but the Warcraft client tries to verify that it's communicating with official servers (which is why you need w3l to connect to PvPGN and why gproxy uses LAN functionality by default).

**Comment by AncientiCe** [comment]
But using the same logic as man in the middle shouldn’t it be easier to
dump the w3l since its harder to patch for 1.29 and intercept the auth
packages (cdkey check, server eligibility check) ?

**Comment by nielsAD** [comment]
Before 1.30.2, there's a RSA verification of the server IP. After 1.30.2, there's a TLS server certificate verification. If you want the client to connect to a non-official server (i.e. PvPGN or your intercept program), you need to disable these checks, which is what w3l does, you can't disable them by altering packets.

**Comment by AncientiCe** [comment]
Thanks for the assistance!
